### PR TITLE
added allauth templates and base templates

### PR DESCRIPTION
**Pull request by Atinos31**
added allauth and base templates

### CODE REVIEW

**Comment by Atinos31** [comment]
home app added(index.html template , views and urls)

**Comment by RvN-R** [comment]
Great stuff, just looking over this both commits. The commit "added allauth teamplates and base templates" has an issue on templates/index.html, don't see any block or endblocks ? I think you have fixed this in the next commit "home app added(index.html template, views and urls". Are both commits under one pull request ? I.e if we approve this will both commits get pushed to main ? Or are they separate pull requests that both need approving?

**Comment by Atinos31** [comment]
yes both commits will be added to main

**Review by RvN-R — APPROVED** [review]
All looks good apart from lack of block and endblock in templates/base.html. You've fixed that in the next commit. So will approve this and then approve the next commit as well.

**Review by RvN-R — APPROVED** [review]

**Pull request merged**
