### PR TITLE
 breathing relax app done

### PR DESCRIPTION
**Pull request by Atinos31**
tweaked some styles, breathin app connected to another css and js files in static. i did this so not to crash up the code. hope it works well.

### CODE REVIEW

**Comment by Atinos31** [comment]
crispy forms uncommented out

**Comment by debbiect246** [comment]
thank you Sandra

**Comment by debbiect246** [comment]
ok

**Comment by debbiect246** [comment]
ok that looks fine

**Comment by debbiect246** [comment]
breath app looks fine

**Comment by debbiect246** [comment]
ok

**Comment by debbiect246** [comment]
ok

**Comment by Atinos31** [comment]
emails confirmations done

**Pull request closed without merging**
